### ISSUE TITLE
UI-Utils Validate problem

### ISSUE THREAD

**Issue by iegorov** [angular-ui/community#3]
ui-validate does not work properly with Bootstrap 3.2.0 because there are no CSS rules 
input:focus:invalid,
textarea:focus:invalid,
select:focus:invalid {
  color: #b94a48;
  border-color: #ee5f5b;
}

**Comment by ProLoser** [comment]
It's not the responsibility of `ui-validate` to apply CSS or classes. It simply is a convenience wrapper for adding angular validation rules.
